# This file is autogenerated from update.sh in the parent directory.
{
  dev = {
    version = "48.0.2547.0";
    sha256 = "11py0nrrc0jkb42nmrm195mc5l9kqpzcaj5na9w1y6fmr5h2rlwi";
    sha256bin32 = "1rpi1n4i0z7zvwjhkfhr7xcx6xpb2hxpzr9zi7nmfnjrmdm15syr";
    sha256bin64 = "1ikjs8pwx3a5gaczpwwagf5wbyvzqrc5wrcdrpn11xxkg3p12wwb";
  };
  beta = {
    version = "47.0.2526.27";
    sha256 = "1riqsgx9hxfvgwssl157fj64pwpihrrvxdyylvlnawh0yhwhww6v";
    sha256bin32 = "17czvjgbyxmdv2cq6hbrbmbhzvas9s4p20f4k6b55idly0a01xvh";
    sha256bin64 = "0laymx8gddnhwniwih1hc1wzmvirmqh4d1qj3fa3ynf7qnva1xi4";
  };
  stable = {
    version = "46.0.2490.80";
    sha256 = "0gzy2d4x4cpd6hx9x25fwxs38y2q04afvl6rh3glzd348qli11py";
    sha256bin32 = "1cg6693x76l6y9zqadp7hwav904ryyp6bgf4xmhxk0ql5d9wsgvd";
    sha256bin64 = "11awl7nn4vxv07k0j3kxpdy9z7mwylblwlk5mb2r507nk5lsqzrh";
  };
}
