# This file is autogenerated from update.sh in the same directory.
{
  beta = {
    sha256 = "1lpgkf292f6v6v19zjp1si6vvizixk9192yjx76pq1d790678qrb";
    sha256bin64 = "028c3gjh5zbxr53wkk3s5jvgwc2fz9cnvnyr58q4la91vyrbjslm";
    version = "74.0.3729.61";
  };
  dev = {
    sha256 = "1g8ynjc957bbfg0123vdy7q9j5ggv2dxix0h6a6nlkscrwqy03vk";
    sha256bin64 = "1z3php15n1xlwqwvl5bkppwrvzc99y70lv84jzjahh83a5w5ksqm";
    version = "72.0.3626.7";
  };
  stable = {
    sha256 = "0j84shpz5a1zycjn6vknqmqscrsalvlazkirq1maa3psz8m5ddh7";
    sha256bin64 = "0000000000000000000000000000000000000000000000000000000000000000";
    version = "72.0.3626.122";
  };
  ungoogled = {
    sha256 = "0bwlq5xii26b3yngwkwb7l2mx03c30ffpym4xg0hcci8ry7zhpj4";
    version = "72.0.3626.122-4";
  };
}
