# This file is autogenerated from update.sh in the same directory.
{
  beta = {
    sha256 = "1lpgkf292f6v6v19zjp1si6vvizixk9192yjx76pq1d790678qrb";
    sha256bin64 = "0fg6z15ayp16lkqak7mhyrya1884sm7mfb5ma2hcmd1gcxnvszx6";
    version = "74.0.3729.75";
  };
  dev = {
    sha256 = "0agf2y7nx7dmj7mq10r97c5rl8xavkj3nbwsv1mfgbb2zw70f67z";
    sha256bin64 = "0y9gxbv19m94lypmpqq9m1jfbafmn50rxx717hb3bghjpqq80n4p";
    version = "75.0.3759.4";
  };
  stable = {
    sha256 = "1bskjr7yiwvdab1b5mp36y6964xqpgks6dqazm4qifwqvqcw80pb";
    sha256bin64 = "00ndrqhmnk567sw6xj22m84126qvivq0jzfx0v46ya3kq6ln22gr";
    version = "73.0.3683.103";
  };
  ungoogled = {
    sha256 = "0j84shpz5a1zycjn6vknqmqscrsalvlazkirq1maa3psz8m5ddh7";
    version = "72.0.3626.122";
  };
}
