# This file is autogenerated from update.py in the same directory.
{
  icedtea7 = rec {
    version = "2.6.19";

    url = "http://icedtea.wildebeest.org/download/source/icedtea-${version}.tar.xz";
    sha256 = "0z97p9x6dkbl77pp2xhbzisp0xm8qi50g5hrgpr678bh77nd581b";

    common_url = "http://icedtea.classpath.org/download/drops/icedtea7/${version}";

    bundles = {
      openjdk = rec {
        url = "${common_url}/openjdk.tar.bz2";
        sha256 = "2531838d9cf08755d88c91498da6fef427000d0fd527c7ddeaa60c993aa679ea";
      };

      corba = rec {
        url = "${common_url}/corba.tar.bz2";
        sha256 = "aae916ff4c1f3cbdb14f57716d03adf1f2d9cb221bf0fa0580f607d7a360245b";
      };

      jaxp = rec {
        url = "${common_url}/jaxp.tar.bz2";
        sha256 = "4545cf0b2bfeca6cd019f1c8bab3ed7317963776b859f80ffc4d8d79d3c82e8f";
      };

      jaxws = rec {
        url = "${common_url}/jaxws.tar.bz2";
        sha256 = "9b2b76598996962c5128e586edded4022e162421d9898a57c3d6dce2fbe7ee6b";
      };

      jdk = rec {
        url = "${common_url}/jdk.tar.bz2";
        sha256 = "1653315e15f30f4f250d6ec9085043b534a28c293ba445467e274c56fef84b88";
      };

      langtools = rec {
        url = "${common_url}/langtools.tar.bz2";
        sha256 = "d9d02a7f135350d66d2dde28dad7f2257843d11cc663b641740b1cf21ec3d710";
      };

      hotspot = rec {
        url = "${common_url}/hotspot.tar.bz2";
        sha256 = "fbbfa17c95891491311758d2ef595ec322c46452e0bf7b51eb42a9ca1ccc419b";
      };
    };
  };
}
